### ISSUE TITLE
wasentha.com

### ISSUE THREAD

**Issue by wasentha** [realbig/RBM_TH_SPIRIT_OF_MOSAIC_ART#10]
Hello Eric,
Below is what I received from my subscription to Wasentha.com  - non of the content is showing.

Thanks,
## Wasentha

Begin forwarded message:

From: Wasentha Young wasentha@me.com
Date: May 01, 2016 7:02:00 AM
To: wasentha@me.com
Subject: New from wasentha.com for 05/01/2016
# 

You are receiving this email because you opted in at my website, http://wasentha.com.

Unsubscribe wasentha@me.com from this list:
http://peacefuldragonschool.us8.list-manage2.com/unsubscribe?u=fa0d7ab5402eeb0ebba4082b8&id=31d37ab87a&e=9c7524531d&c=efa941d66b

Our mailing address is:
Wasentha Young, MA
P.O. Box 7034
Ann Arbor, MI 48107
USA

Our telephone:
734-741-0695

Forward this email to a friend:
http://us8.forward-to-friend1.com/forward?u=fa0d7ab5402eeb0ebba4082b8&id=efa941d66b&e=9c7524531d

Update your profile:
http://peacefuldragonschool.us8.list-manage1.com/profile?u=fa0d7ab5402eeb0ebba4082b8&id=31d37ab87a&e=9c7524531d

**Comment by d4mation** [comment]
This issue was moved to realbig/RBM_TH_WASENTHA#42

**Comment by d4mation** [comment]
Moved to realbig/RBM_TH_WASENTHA#42
