### ISSUE TITLE
spiritofmosaicart.com doesn't work

### ISSUE THREAD

**Issue by wasentha** [realbig/RBM_TH_SPIRIT_OF_MOSAIC_ART#11]
When I try to go to spiritofmosaicart.com I am still getting some other company that says it will be coming to soon to register.com....

**Comment by d4mation** [comment]
That's very interesting. It definitely should have propagated through the DNS by now...

I've tweaked some things in the settings for your Domain, so hopefully that will change for us soon.

**Comment by d4mation** [comment]
In the meantime, http://spiritofmosaicart.realbigwebsites.com does work.

**Comment by d4mation** [comment]
http://spiritofmosaicart.com/ now works once again. I fixed up the DNS Records this morning and now that they've propagated, I've updated the database for your website to match.
