### ISSUE TITLE
Header Images on Pages based on Featured Image

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_SPIRIT_OF_MOSAIC_ART#3]
Seems to be the best way to handle this.

**Comment by d4mation** [comment]
![image](https://cloud.githubusercontent.com/assets/7770631/13997125/e7c6ebfe-f106-11e5-91d8-7a4eeb6c1dc3.png)

The image used for most examples isn't full-width, but rather just that small center part. The pattern behind it masks that fact unless you look closely.

Not sure if we should implement the same pattern, or give a color-picker to choose a background-color. A color-picker would be more universal, but it would be more noticeable.

A color overlay over the pattern could work, but that would lead to some nasty DOM. We also don't have access to this particular pattern.

**Comment by d4mation** [comment]
@wasentha

What do you think about this? It can be handled in a lot of different ways. Even if you wanted to just make sure the images are wide enough to stretch across the page that would be fine.

**Comment by wasentha** [comment]
I like the patterns behind the mask... it does not detract for the art piece.

**Comment by d4mation** [comment]
Could you send us the file for the background pattern? We don't have a way to grab that to use for the header images.

**Comment by wasentha** [comment]
I did not make the background pattern on this. I think they took the sheet behind the skull, repeated the patterns in varied rotations and added a bit of color to make that pattern - or had that pattern. I'll look into powerpoint and see if I can find anything.
Wasentha YoungDirector 
www.peacefuldragonschool.com
734-741-0695
wasentha@peacefuldragonschool.com 

---- On Mon, 04 Apr 2016 08:19:38 -0400 Eric Defore &lt;notifications@github.com&gt; wrote ---- 

Could you send us the file for the background pattern? We don't have a way to grab that to use for the header images.

**Comment by d4mation** [comment]
Were you able to find anything in PowerPoint?

It's possible that a pattern could have been extrapolated from the colors behind the skull.

We could do something similar to that, kind of like [this](http://qrohlf.com/trianglify/). However, it would look a little different every time the page loads as it regenerates the pattern every time. We could set it to use certain colors though, so the colors would not be random.

**Comment by BigActual** [comment]
@d4mation- Does it need to be dynamically generated every time, in this use case?

**Comment by d4mation** [comment]
Using a library like the ones I've found to create a pattern like that, it would need to be dynamically generated each time.

Otherwise, we will need to upload the pattern as a separate image to use as a background or upload the skull image with it as a background in order to make it fit the width of the page. These options are perfectly fine, but if @wasentha can't find the pattern image, we may need to generate it on-the-fly.

**Comment by wasentha** [comment]
Hello,
I am out of town right now. What is the url that I can go to, so I can see what you are talking about. Thanks.

Wasentha Young - Sent from my iPad

**Comment by d4mation** [comment]
I haven't implemented this feature yet since we're still figuring out how to handle it, but the URL is currently http://spiritofmosaicart.realbigwebsites.com/

I had it at http://spiritofmosaicart.com up until just recently, when that domain strangely stopped working.

**Comment by d4mation** [comment]
@wasentha

I implemented the background image you sent via e-mail in my local copy as an Option that would apply to every Page you added a Header Image to (Since you said to use it for all of them)

I set it up similarly to the screenshots you had on Dropbox.

![image](https://cloud.githubusercontent.com/assets/7770631/14649727/5d72e4a4-0636-11e6-9254-5c12f1b2c9d2.png)

I'm not sure how I feel about it. I don't think it works quite right&mdash;at least not with the Skull image. It really calls attention to the fact that they are two separate images due to the difference in color between the two.

Something I just thought of that could remedy this would be to convert the background image to be grayscale and then I could provide a color option so that you could put a color overlay on-top of it to force it to match whatever you need it to.

It's not the cleanest way to solve this problem, but that would allow you to use the same pattern on each page easily.

What do you think?

**Comment by wasentha** [comment]
Yes on the grayscale - great idea!

Wasentha YoungDirector 
www.peacefuldragonschool.com
734-741-0695
wasentha@peacefuldragonschool.com 

---- On Tue, 19 Apr 2016 14:01:01 -0400 Eric Defore &lt;notifications@github.com&gt; wrote ---- 

@wasentha
 I implemented the background image you sent via e-mail in my local copy as an Option that would apply to every Page you added a Header Image to (Since you said to use it for all of them)
 I set it up similarly to the screenshots you had on Dropbox.

 I'm not sure how I feel about it. I don't think it works quite right—at least not with the Skull image. It really calls attention to the fact that they are two separate images due to the difference in color between the two.
 Something I just thought of that could remedy this would be to convert the background image to be grayscale and then I could provide a color option so that you could put a color overlay on-top of it to force it to match whatever you need it to.
 It's not the cleanest way to solve this problem, but that would allow you to use the same pattern on each page easily.
 What do you think?

**Comment by d4mation** [comment]
I've converted the Header Background Image to Grayscale and set up a way for the an overlay color placed on top of it to help the overlay match whatever Image gets placed on top of the Header Background Image. The Opacity of the Overlay can be adjusted as well, in case you want the pattern to show through more.

For the Skull Image it made the most sense to set the Overlay to another gray even though the image was already gray, as it helps to smooth out the colors in the image a little as well as match a bit better.

With the Overlay:
![image](https://cloud.githubusercontent.com/assets/7770631/14680446/5944709a-06eb-11e6-842c-037128133df9.png)

Without the Overlay:
![image](https://cloud.githubusercontent.com/assets/7770631/14680522/9b220112-06eb-11e6-9a06-b28aa352973a.png)

Here's a look at the Controls for the Individual Page:
![image](https://cloud.githubusercontent.com/assets/7770631/14680411/3d4c9d68-06eb-11e6-9793-471d3013148b.png)

And here's a look at how the Global Header Background Image is set:
![image](https://cloud.githubusercontent.com/assets/7770631/14680637/f424f922-06eb-11e6-893e-d7eac4883cde.png)

What do you think, @wasentha?

**Comment by wasentha** [comment]
I like it better without the overlay

**Comment by d4mation** [comment]
Alrighty, the Overlay gets applied on a Page-By-Page basis, so you can always decide whether to use the Overlay or not if it happens to look better for a certain Header Image.

This can be seen on the About the Artists page here: http://spiritofmosaicart.realbigwebsites.com/about-the-artists/

You may need to Hard-Refresh the page (`CTRL+F5` on a PC, `CMD+SHIFT+R` on a Mac) to see the changes.

**Comment by wasentha** [comment]
Good - having the choice works well.
