### ISSUE TITLE
Change Font Families

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_SPIRIT_OF_MOSAIC_ART#4]
Using defaults still.

**Comment by d4mation** [comment]
WhatTheFont can't figure out what they are based on the provided Screenshots.
![image](https://cloud.githubusercontent.com/assets/7770631/13991072/08238ffc-f0ed-11e5-834b-38e5410b56b8.png)

**Comment by d4mation** [comment]
@wasentha

Which fonts were you using for the mockup of this site that you made? I want to be sure I can set things up the way that you want them to be.

**Comment by wasentha** [comment]
The Spirit = Franklin Gothic Demi
of Mosaic Art = Franklin Gothic Book

**Comment by d4mation** [comment]
Excellent, thank you!
