### ISSUE TITLE
Whether or not to have a main Sidebar

### ISSUE THREAD

**Issue by d4mation** [realbig/RBM_TH_SPIRIT_OF_MOSAIC_ART#6]
None of the screenshots on Dropbox show a Sidebar on the interior pages.

Some of the content layout actually interferes with a Sidebar (Full-width content).

I'm not sure if that was a limitation of the software that was used to create those mockups, or if they are simply not desired on this site.

**Comment by d4mation** [comment]
@wasentha

Were you wanting a Sidebar for this site?

**Comment by wasentha** [comment]
There is no side bar. That was just the dashboard.

**Comment by d4mation** [comment]
So the site isn't intended to have a Sidebar at all? I figured I could see to the left was just the dashboard for the site builder you were using, but are you wanting to have something like on wasentha.com where it shows Recent Posts in a sidebar? We could put many other things there as well.

**Comment by d4mation** [comment]
@wasentha Just looking for clarification on this

**Comment by wasentha** [comment]
That sounds good - Recent posts as a sidebar.

**Comment by d4mation** [comment]
This is in place on the About the Artists page: http://spiritofmosaicart.realbigwebsites.com/about-the-artists/

All the other page layouts as seen in the Mockups on Dropbox don't really allow for a Sidebar. Would you only want it visible on the About the Artists page?

**Comment by d4mation** [comment]
It is also on the Gallery page: http://spiritofmosaicart.realbigwebsites.com/gallery/

**Comment by wasentha** [comment]
The sidebar on just those two pages works just fine.
