### ISSUE TITLE
Phone number on home page

### ISSUE THREAD

**Issue by wasentha** [realbig/RBM_TH_SPIRIT_OF_MOSAIC_ART#7]
The phone number on the cover page is incorrect. That was one of theirs. The number is the same as the contact page: 734-741-0695

**Comment by d4mation** [comment]
All fixed!

![image](https://cloud.githubusercontent.com/assets/7770631/14797303/15cb1986-0b00-11e6-9c0a-443abd79b26d.png)

**Comment by d4mation** [comment]
Referencing #9

**Comment by wasentha** [comment]
I'm still seeing it

**Comment by d4mation** [comment]
Just ensured the cache was cleared on the Server. Hard-refreshing on your end should clear it up now.
