### ISSUE TITLE
Different logo photo

### ISSUE THREAD

**Issue by wasentha** [realbig/RBM_TH_SPIRIT_OF_MOSAIC_ART#8]
I am assuming that I will be able to change the logo photo? I don't like that one it was just a placement holder.

**Comment by d4mation** [comment]
Yep, you are able to change the logo photo whenever you'd like through the Customizer Menu.

![image](https://cloud.githubusercontent.com/assets/7770631/14797267/ed27b836-0aff-11e6-9adf-48986b6ae0a1.png)

**Comment by wasentha** [comment]
Good thanks

Wasentha YoungDirector 
www.peacefuldragonschool.com
734-741-0695
wasentha@peacefuldragonschool.com 

---- On Mon, 25 Apr 2016 16:08:25 -0400 Eric Defore &lt;notifications@github.com&gt; wrote ---- 

Yep, you are able to change the logo photo whenever you'd like through the Customizer Menu.
