### ISSUE TITLE
Nope - Please delete the phone icon and the number is (734) 741-0695

### ISSUE THREAD

**Issue by wasentha** [realbig/RBM_TH_SPIRIT_OF_MOSAIC_ART#9]
Not sure what that other number is....

**Comment by wasentha** [comment]
Just remove the phone number all together. And then it's done. Thanks

**Comment by d4mation** [comment]
Went ahead and removed it. You can comment on Issues that I Close, so if there's an error on something like this (I'm not sure how I got the wrong number either&mdash;I copy/pasted it) I can always re-Open them and we can work from there instead of creating a new Issue :)

**Comment by wasentha** [comment]
I tried to comment after you closed and it would not allow me to.

**Comment by wasentha** [comment]
hmm

**Comment by d4mation** [comment]
That is pretty strange. I'm not sure why that would have happened. 😕

**Comment by wasentha** [comment]
I refreshed and it is off of the home page, but not the About the Artist page.

**Comment by d4mation** [comment]
Hmm, that shouldn't be the case. Both of those pages use the same file for all the stuff in the Header.

Did you do a normal refresh or a Hard-Refresh? (`CTRL+F5` on a PC, `CMD+SHIFT+R` on a Mac)

**Comment by wasentha** [comment]
Yup, I'll try again.

**Comment by wasentha** [comment]
All is well. I had to use chrome instead of explorer

**Comment by wasentha** [comment]
looks better without it. thanks
